5 модуль задачи
js-tasks-ru/jsbasic-20230629_ed41658 pull request #6
Opened 2023-07-22 06:20 UTC by kindgilya

2023-07-22 06:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-22 19:18 UTC, SinimaWath requested changes

2023-07-22 19:18 UTC, SinimaWath commented on 5-module/2-task/index.js
> +      : (tekstik.hidden = false)
- это условие нужно упростить до: `tekstik.hidden = !tekstik.hidden`
- кажется название переменной tekstik, не очень подходящее

2023-07-22 19:18 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  tekstik = document.getElementById("text");
Это не обьявления переменных, а добавления в глобальный обьект. Используй здесь const

2023-07-24 05:54 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-24 05:54 UTC, kindgilya commented on 5-module/2-task/index.js
> +  tekstik = document.getElementById("text");
Добрый день! Всё исправила, спасибо за комментарии)

2023-07-25 12:37 UTC, merged